export interface StyleSystem {
  id: string;
  name: string;
  description: string;
  palette: { primary: string; accent: string; surface: string; text: string; muted: string };
  typography: { display: string; body: string; mono?: string };
  spacing: { unit: number; grid: number };
  borderRadius: string;
  shadow: string;
  tags: string[];
}

const S: StyleSystem[] = [
  // === Minimal / Clean (1-8) ===
  { id:"minimal-white",name:"极简白",description:"White space, clean lines, single accent",palette:{primary:"#18181B",accent:"#F43F5E",surface:"#FAFAFA",text:"#09090B",muted:"#A1A1AA"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"8px",shadow:"0 1px 3px rgba(0,0,0,0.08)",tags:["clean","minimal","modern","white"] },
  { id:"clean-corporate",name:"简洁企业",description:"Professional, trustworthy, blue-grey",palette:{primary:"#1E3A5F",accent:"#4A90D9",surface:"#F8FAFC",text:"#1E293B",muted:"#94A3B8"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"6px",shadow:"0 1px 3px rgba(0,0,0,0.1)",tags:["corporate","B2B","professional","clean"] },
  { id:"soft-minimal",name:"柔和极简",description:"Soft tones, rounded, approachable",palette:{primary:"#E8A0B4",accent:"#F5C6A0",surface:"#FDF8F5",text:"#3D2C2E",muted:"#8A7A7C"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"16px",shadow:"0 4px 16px rgba(0,0,0,0.06)",tags:["soft","warm","feminine","friendly"] },
  { id:"warm-editorial",name:"温暖编辑",description:"Serif display, warm cream, editorial feel",palette:{primary:"#D97757",accent:"#8C6E5D",surface:"#FDF8F5",text:"#3D3D3D",muted:"#9C8B88"},typography:{display:"'Georgia',serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:32},borderRadius:"4px",shadow:"0 2px 8px rgba(0,0,0,0.06)",tags:["editorial","warm","serif","magazine"] },
  { id:"cold-minimal",name:"冷感极简",description:"Crisp whites, cool greys, sharp edges",palette:{primary:"#1E1E2E",accent:"#6C63FF",surface:"#FAFBFC",text:"#24292E",muted:"#8B949E"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"4px",shadow:"0 1px 2px rgba(0,0,0,0.06)",tags:["clean","modern","tech","sharp"] },
  { id:"airy-light",name:"空气感",description:"Maximum whitespace, feather-light, open",palette:{primary:"#2D3436",accent:"#00B894",surface:"#FFFFFF",text:"#2D3436",muted:"#B2BEC3"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:12,grid:48},borderRadius:"12px",shadow:"0 2px 12px rgba(0,0,0,0.04)",tags:["light","airy","open","spacious"] },
  { id:"mono-chrome",name:"单色主义",description:"Black, white, one accent, pure contrast",palette:{primary:"#000000",accent:"#FFFFFF",surface:"#FFFFFF",text:"#000000",muted:"#888888"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"0px",shadow:"0 0 0 1px rgba(0,0,0,0.1)",tags:["monochrome","bold","contrast","minimal"] },
  { id:"quiet-neutral",name:"安静中性",description:"Beige tones, calm, understated elegance",palette:{primary:"#5D5A54",accent:"#A0927A",surface:"#F7F5F0",text:"#3D3A36",muted:"#A8A39A"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"8px",shadow:"0 2px 8px rgba(0,0,0,0.05)",tags:["neutral","calm","elegant","understated"] },

  // === Bold / Dramatic (9-16) ===
  { id:"dark-luxury",name:"深色奢华",description:"Dark background, gold accent, premium feel",palette:{primary:"#0D0D0D",accent:"#C9A84C",surface:"#1A1A1A",text:"#E8E8E8",muted:"#8A8A8A"},typography:{display:"'Playfair Display',serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"8px",shadow:"0 4px 20px rgba(0,0,0,0.3)",tags:["dark","luxury","premium","gold"] },
  { id:"bold-contrast",name:"大胆对比",description:"High contrast, oversized type, maximal",palette:{primary:"#000000",accent:"#FF2D55",surface:"#FFFFFF",text:"#000000",muted:"#6B7280"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"0px",shadow:"0 8px 32px rgba(0,0,0,0.12)",tags:["bold","contrast","maximal","loud"] },
  { id:"editorial-monocle",name:"编辑式克制",description:"Deep navy, red accent, serif, restrained",palette:{primary:"#1A1A2E",accent:"#C44536",surface:"#FAF8F5",text:"#2D2D2D",muted:"#8E8E8E"},typography:{display:"'Georgia',serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:32},borderRadius:"2px",shadow:"0 2px 8px rgba(0,0,0,0.08)",tags:["editorial","serif","restrained","navy"] },
  { id:"night-owl",name:"夜猫",description:"Deep purple, neon green, dark mode native",palette:{primary:"#0F0A2E",accent:"#00FFAA",surface:"#1A163F",text:"#E0E0FF",muted:"#7B75A8"},typography:{display:"'Space Grotesk',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"12px",shadow:"0 4px 24px rgba(0,255,170,0.1)",tags:["dark","neon","gaming","futuristic"] },
  { id:"sunset-warm",name:"日落暖",description:"Warm gradients, orange/pink, energetic",palette:{primary:"#FF6B35",accent:"#FF2E63",surface:"#FFF8F0",text:"#2C2C2C",muted:"#A0A0A0"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"16px",shadow:"0 8px 32px rgba(255,107,53,0.15)",tags:["warm","gradient","energetic","sunset"] },
  { id:"deep-ocean",name:"深海",description:"Deep blues, teal accent, professional depth",palette:{primary:"#0A1628",accent:"#00D4AA",surface:"#0F1D32",text:"#E2E8F0",muted:"#64748B"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"8px",shadow:"0 4px 20px rgba(0,0,0,0.3)",tags:["dark","ocean","professional","tech"] },
  { id:"royal-purple",name:"皇家紫",description:"Rich purple, gold, majestic",palette:{primary:"#2D1B69",accent:"#D4AF37",surface:"#1A0F3F",text:"#F0E6FF",muted:"#9A89C0"},typography:{display:"'Playfair Display',serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"12px",shadow:"0 8px 32px rgba(212,175,55,0.15)",tags:["purple","royal","premium","gold"] },

  // === Tech / Modern (17-24) ===
  { id:"tech-utility",name:"科技实用",description:"Neutral, green accent, data-driven clean",palette:{primary:"#1E1E2E",accent:"#00E698",surface:"#FAFBFC",text:"#24292E",muted:"#8B949E"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"6px",shadow:"0 1px 3px rgba(0,0,0,0.08)",tags:["tech","data","clean","neutral"] },
  { id:"glassmorphism",name:"玻璃拟态",description:"Frosted glass, blurred backgrounds, light",palette:{primary:"rgba(255,255,255,0.1)",accent:"#6C63FF",surface:"rgba(255,255,255,0.05)",text:"#1A1A2E",muted:"rgba(0,0,0,0.4)"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"16px",shadow:"0 8px 32px rgba(0,0,0,0.1)",tags:["glass","modern","trendy","creative"] },
  { id:"neo-brutalism",name:"新粗野主义",description:"Bold borders, raw colors, unapologetic",palette:{primary:"#FF6B35",accent:"#0047AB",surface:"#FFE500",text:"#000000",muted:"#6B7280"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"0px",shadow:"8px 8px 0 rgba(0,0,0,1)",tags:["brutalist","bold","raw","colorful"] },
  { id:"neumorphism",name:"新拟态",description:"Soft shadows, inset depth, subtle",palette:{primary:"#E0E5EC",accent:"#6C63FF",surface:"#E0E5EC",text:"#2D4059",muted:"#A3B1C6"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"16px",shadow:"9px 9px 16px rgba(163,177,198,0.6), -9px -9px 16px rgba(255,255,255,0.5)",tags:["neumorphic","soft","subtle","modern"] },
  { id:"cyberpunk",name:"赛博朋克",description:"Neon pink/cyan, dark, futuristic grid",palette:{primary:"#0A0A0A",accent:"#FF00FF",surface:"#1A1A2E",text:"#00FFFF",muted:"#6B7280"},typography:{display:"'Space Grotesk',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"4px",shadow:"0 0 20px rgba(255,0,255,0.3)",tags:["cyberpunk","neon","futuristic","gaming"] },
  { id:"gradient-flow",name:"渐变流动",description:"Smooth gradients, purple/blue/teal flow",palette:{primary:"#6C3BD6",accent:"#00D4AA",surface:"#FAFBFF",text:"#1A1A2E",muted:"#8B949E"},typography:{display:"'Space Grotesk',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"12px",shadow:"0 4px 24px rgba(108,59,214,0.15)",tags:["gradient","purple","modern","creative"] },
  { id:"skeuomorphic",name:"拟物化",description:"Realistic textures, depth, rich materials",palette:{primary:"#8B4513",accent:"#D4AF37",surface:"#F5F0E8",text:"#2C1810",muted:"#8B7355"},typography:{display:"'Georgia',serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"8px",shadow:"inset 0 2px 4px rgba(0,0,0,0.1), 0 4px 12px rgba(0,0,0,0.1)",tags:["skeuomorphic","realistic","textured","warm"] },
  { id:"flat-design",name:"扁平设计",description:"Clean flat colors, no shadows, simple",palette:{primary:"#2C3E50",accent:"#E74C3C",surface:"#ECF0F1",text:"#2C3E50",muted:"#95A5A6"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"0px",shadow:"none",tags:["flat","simple","clean","classic"] },

  // === Playful / Creative (25-32) ===
  { id:"playful-color",name:"多彩趣味",description:"Colorful, organic shapes, lighthearted",palette:{primary:"#FF6B6B",accent:"#4ECDC4",surface:"#FFF8F0",text:"#2C3E50",muted:"#8C8C8C"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"20px",shadow:"0 8px 24px rgba(255,107,107,0.2)",tags:["colorful","playful","fun","creative"] },
  { id:"pastel-dream",name:"粉彩梦境",description:"Soft pastels, rounded, dreamy",palette:{primary:"#A8D8EA",accent:"#F3A3B8",surface:"#FDF8F5",text:"#4A4A4A",muted:"#B0B0B0"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"24px",shadow:"0 4px 16px rgba(168,216,234,0.3)",tags:["pastel","soft","dreamy","cute"] },
  { id:"kawaii-japan",name:"可爱日系",description:"Cute Japanese inspired, soft pinks, playful",palette:{primary:"#FF9BB3",accent:"#FEC8D8",surface:"#FFF5F7",text:"#5C3D4A",muted:"#B58B9A"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"24px",shadow:"0 4px 16px rgba(255,155,179,0.25)",tags:["cute","kawaii","japanese","feminine"] },
  { id:"retro-vintage",name:"复古怀旧",description:"Warm vintage tones, grain texture, nostalgic",palette:{primary:"#8B5E3C",accent:"#D4A76A",surface:"#F5E6D3",text:"#3D2B1F",muted:"#A0846A"},typography:{display:"'Georgia',serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"4px",shadow:"0 2px 8px rgba(0,0,0,0.1)",tags:["vintage","retro","warm","nostalgic"] },
  { id:"memphis-play",name:"孟菲斯",description:"80s Memphis style, geometric, bold colors",palette:{primary:"#FF5733",accent:"#33FFCE",surface:"#FFFFFF",text:"#1A1A1A",muted:"#888888"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"0px",shadow:"4px 4px 0 rgba(0,0,0,0.2)",tags:["memphis","80s","geometric","retro"] },
  { id:"doodle-hand",name:"手绘涂鸦",description:"Hand-drawn style, imperfect lines, charming",palette:{primary:"#2C3E50",accent:"#FF6B6B",surface:"#FFFAF0",text:"#2C3E50",muted:"#95A5A6"},typography:{display:"'Comic Sans MS',cursive",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"16px",shadow:"2px 2px 0 rgba(0,0,0,0.1)",tags:["doodle","hand-drawn","playful","charming"] },
  { id:"tropical-vibe",name:"热带风情",description:"Bright tropical colors, lush, energetic",palette:{primary:"#2ECC71",accent:"#F1C40F",surface:"#FFF9E6",text:"#1A3A2A",muted:"#7A9A8A"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"16px",shadow:"0 8px 24px rgba(46,204,113,0.2)",tags:["tropical","bright","nature","summer"] },
  { id:"color-block",name:"色块拼接",description:"Large color blocks, Bauhaus inspired",palette:{primary:"#E74C3C",accent:"#3498DB",surface:"#F1C40F",text:"#2C3E50",muted:"#95A5A6"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"0px",shadow:"0 4px 16px rgba(0,0,0,0.1)",tags:["color-block","bauhaus","bold","graphic"] },

  // === Nature / Organic (33-40) ===
  { id:"nature-organic",name:"自然有机",description:"Earthy greens, organic shapes, grounded",palette:{primary:"#2D6A4F",accent:"#95B46A",surface:"#F6F7F4",text:"#1B2F22",muted:"#7A9A7A"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"12px",shadow:"0 4px 16px rgba(45,106,79,0.15)",tags:["nature","organic","earth","green"] },
  { id:"forest-deep",name:"森林深绿",description:"Deep forest greens, natural textures",palette:{primary:"#1B4332",accent:"#7CB342",surface:"#F0F7F0",text:"#1B4332",muted:"#6B8E6B"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"8px",shadow:"0 4px 16px rgba(27,67,50,0.15)",tags:["forest","nature","deep","calm"] },
  { id:"desert-warm",name:"沙漠暖色",description:"Warm terracotta, sand tones, arid beauty",palette:{primary:"#C45A3C",accent:"#E8B87A",surface:"#FDF6EC",text:"#3D2B1F",muted:"#A0846A"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"12px",shadow:"0 4px 16px rgba(196,90,60,0.15)",tags:["desert","terracotta","warm","earthy"] },
  { id:"ocean-breeze",name:"海风",description:"Coastal blues, sandy beige, fresh",palette:{primary:"#006994",accent:"#F4A460",surface:"#F0F8FF",text:"#1A3A4A",muted:"#7A9AAA"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"12px",shadow:"0 4px 16px rgba(0,105,148,0.12)",tags:["ocean","coastal","fresh","calm"] },
  { id:"garden-bloom",name:"花园绽放",description:"Floral pinks, sage green, fresh bloom",palette:{primary:"#D4739A",accent:"#9CB87A",surface:"#FDF8F5",text:"#3D2C2E",muted:"#8A7A7C"},typography:{display:"'Georgia',serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"20px",shadow:"0 4px 20px rgba(212,115,154,0.15)",tags:["floral","garden","feminine","fresh"] },
  { id:"earthy-terracotta",name:"陶土风",description:"Terracotta, clay, warm earth tones",palette:{primary:"#CC5A41",accent:"#F0C4A0",surface:"#FAF0EA",text:"#3D2B1F",muted:"#9C8B80"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"16px",shadow:"0 4px 16px rgba(204,90,65,0.12)",tags:["terracotta","earthy","warm","clay"] },
  { id:"lavender-field",name:"薰衣草田",description:"Purple lavenders, soft grey, serene",palette:{primary:"#967BB6",accent:"#D4C4E8",surface:"#F8F6FA",text:"#2D2A3D",muted:"#9A8DA8"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"16px",shadow:"0 4px 16px rgba(150,123,182,0.15)",tags:["lavender","purple","calm","serene"] },
  { id:"sunflower",name:"向日葵",description:"Sunny yellow, sky blue, optimistic",palette:{primary:"#FFD93D",accent:"#6BCB77",surface:"#FFFDF5",text:"#2C3E50",muted:"#95A5A6"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"16px",shadow:"0 8px 24px rgba(255,217,61,0.2)",tags:["sunny","yellow","optimistic","bright"] },

  // === Professional / Enterprise (41-48) ===
  { id:"corporate-trust",name:"企业信赖",description:"Blue, green accent, trustworthy B2B",palette:{primary:"#2563EB",accent:"#059669",surface:"#F8FAFC",text:"#1E293B",muted:"#94A3B8"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"6px",shadow:"0 1px 3px rgba(0,0,0,0.1)",tags:["corporate","B2B","trust","blue"] },
  { id:"financial-blue",name:"金融蓝",description:"Dark blue, gold, conservative, premium",palette:{primary:"#0A1628",accent:"#D4AF37",surface:"#F8F9FA",text:"#1A1A2E",muted:"#6B7280"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"4px",shadow:"0 1px 3px rgba(0,0,0,0.12)",tags:["finance","banking","conservative","premium"] },
  { id:"legal-format",name:"法律规范",description:"Navy, cream, serif, authoritative",palette:{primary:"#1B2A4A",accent:"#C5A572",surface:"#F8F6F0",text:"#2D2D2D",muted:"#8E8E8E"},typography:{display:"'Georgia',serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:32},borderRadius:"2px",shadow:"0 1px 3px rgba(0,0,0,0.08)",tags:["legal","authoritative","serif","navy"] },
  { id:"healthcare-clean",name:"医疗洁净",description:"Clean whites, teal, sterile, calming",palette:{primary:"#00897B",accent:"#4DD0E1",surface:"#F5FAFA",text:"#1A3A3A",muted:"#80A0A0"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"8px",shadow:"0 1px 3px rgba(0,0,0,0.06)",tags:["healthcare","medical","clean","calm"] },
  { id:"nonprofit-soft",name:"公益柔和",description:"Soft greens, warm, approachable, heartfelt",palette:{primary:"#2E7D32",accent:"#66BB6A",surface:"#F5FBF5",text:"#1B3A1B",muted:"#7A9A7A"},typography:{display:"'DM Sans',sans-serif",body:"'DM Sans',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"12px",shadow:"0 4px 12px rgba(46,125,50,0.1)",tags:["nonprofit","green","warm","caring"] },
  { id:"consulting-dark",name:"咨询深色",description:"Dark charcoal, electric blue, smart",palette:{primary:"#1A1A2E",accent:"#4A90D9",surface:"#F5F5F5",text:"#1A1A2E",muted:"#8E8E93"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"4px",shadow:"0 2px 8px rgba(0,0,0,0.08)",tags:["consulting","smart","professional","dark"] },
  { id:"realestate-premium",name:"房产高端",description:"Warm greys, gold accent, aspirational",palette:{primary:"#4A4A4A",accent:"#C5A572",surface:"#FAFAF8",text:"#2D2D2D",muted:"#9E9E9E"},typography:{display:"'Playfair Display',serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:32},borderRadius:"8px",shadow:"0 4px 20px rgba(0,0,0,0.08)",tags:["realestate","premium","aspirational","luxury"] },
  { id:"educational-warm",name:"教育温暖",description:"Warm blues, friendly, encouraging",palette:{primary:"#1565C0",accent:"#FF8F00",surface:"#F8FAFE",text:"#1A2A3A",muted:"#7A8A9A"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"12px",shadow:"0 4px 16px rgba(21,101,192,0.1)",tags:["education","warm","friendly","academic"] },

  // === Creative / Portfolio (49-57) ===
  { id:"portfolio-bold",name:"作品集大胆",description:"Full-bleed imagery, oversized type",palette:{primary:"#000000",accent:"#FFFFFF",surface:"#FFFFFF",text:"#000000",muted:"#888888"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:12,grid:48},borderRadius:"0px",shadow:"none",tags:["portfolio","bold","minimal","creative"] },
  { id:"agency-dark",name:"代理深色",description:"Dark, creative, agency feel",palette:{primary:"#0A0A0A",accent:"#FF3366",surface:"#1A1A1A",text:"#F0F0F0",muted:"#8A8A8A"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"4px",shadow:"0 4px 20px rgba(0,0,0,0.3)",tags:["agency","dark","creative","bold"] },
  { id:"photography",name:"摄影展示",description:"Black background, white text, image first",palette:{primary:"#FFFFFF",accent:"#FF6B35",surface:"#000000",text:"#FFFFFF",muted:"#888888"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:12,grid:48},borderRadius:"0px",shadow:"none",tags:["photography","minimal","dark","visual"] },
  { id:"journalism",name:"新闻纪实",description:"Newspaper inspired, serif, text heavy",palette:{primary:"#000000",accent:"#CC0000",surface:"#F8F6F0",text:"#1A1A1A",muted:"#6B7280"},typography:{display:"'Georgia',serif",body:"'Georgia',serif"},spacing:{unit:8,grid:48},borderRadius:"0px",shadow:"none",tags:["journalism","serif","text","newspaper"] },
  { id:"art-gallery",name:"画廊",description:"White gallery walls, minimal, art focused",palette:{primary:"#FFFFFF",accent:"#1A1A1A",surface:"#FAFAFA",text:"#1A1A1A",muted:"#A0A0A0"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:16,grid:64},borderRadius:"0px",shadow:"none",tags:["gallery","art","minimal","white"] },
  { id:"music-vibe",name:"音乐律动",description:"Dark, vibrant accent, energetic",palette:{primary:"#121212",accent:"#1DB954",surface:"#181818",text:"#FFFFFF",muted:"#B3B3B3"},typography:{display:"'Inter',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"4px",shadow:"0 4px 16px rgba(0,0,0,0.3)",tags:["music","dark","energetic","vibrant"] },
  { id:"fashion-editorial",name:"时尚编辑",description:"High fashion, bold contrast, editorial",palette:{primary:"#000000",accent:"#FF0055",surface:"#FFFFFF",text:"#000000",muted:"#888888"},typography:{display:"'Playfair Display',serif",body:"'Inter',sans-serif"},spacing:{unit:12,grid:48},borderRadius:"0px",shadow:"0 8px 32px rgba(0,0,0,0.12)",tags:["fashion","editorial","bold","premium"] },
  { id:"tech-startup",name:"科技创业",description:"Bright, modern, purple/blue gradient",palette:{primary:"#6C3BD6",accent:"#FF6B6B",surface:"#FFFFFF",text:"#1A1A2E",muted:"#8B949E"},typography:{display:"'Space Grotesk',sans-serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"12px",shadow:"0 8px 24px rgba(108,59,214,0.12)",tags:["startup","modern","bright","purple"] },
  { id:"wedding-elegant",name:"婚礼优雅",description:"Soft rose, gold, romantic, elegant",palette:{primary:"#E8B4B8",accent:"#D4AF37",surface:"#FDF8F5",text:"#3D2C2E",muted:"#B8A0A0"},typography:{display:"'Playfair Display',serif",body:"'Inter',sans-serif"},spacing:{unit:8,grid:24},borderRadius:"24px",shadow:"0 8px 32px rgba(232,180,184,0.2)",tags:["wedding","romantic","elegant","rose"] },
];

export function getStyle(id: string): StyleSystem | undefined {
  return S.find(s => s.id === id);
}

export function searchStyles(query: string): StyleSystem[] {
  const q = query.toLowerCase();
  return S.filter(s => s.tags.some(t => t.includes(q)) || s.name.includes(q) || s.description.toLowerCase().includes(q));
}

export function listStyles(): { id: string; name: string; description: string; tags: string[] }[] {
  return S.map(s => ({ id: s.id, name: s.name, description: s.description, tags: s.tags }));
}

export function getStylesByTag(tag: string): StyleSystem[] {
  return S.filter(s => s.tags.includes(tag.toLowerCase()));
}

export function recommendStyle(industry: string, direction: string): StyleSystem {
  const dir = direction.toLowerCase();
  const ind = industry.toLowerCase();
  const candidates = S.filter(s => s.tags.some(t => t.includes(dir) || t.includes(ind)));
  return candidates[0] || S[0];
}

export { S as STYLES };
